server:
  port: 3001

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: https://	10.11.52.102:7001/eureka/
    register-with-eureka: false
    fetch-registry: false
spring:
  application:
    name: single-provider
